version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ConnectionStrings__DefaultConnectionString=Server=db;Database=BaseConn;User ID=sa;Password=StrongPassword123;TrustServerCertificate=true;

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: baseconn_sqlserver
    environment:
      MSSQL_SA_PASSWORD: StrongPassword123
      ACCEPT_EULA: Y
    hostname: db
    ports:
        - "1433:1433"
